config/routes.rb
Rails.application.routes.draw do
  devise_for :users
  resources :projects do
    resources :tasks, except: %i[index show] 
  end
  root 'projects#index'
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/project.rb
class Project < ApplicationRecord
  belongs_to :user

  def completed? 
    !completed_at.blank? 
  end

  validates :title, presence: true
  validates :description, presence: true
  validates_length_of :title, minimum: 5, maximum: 40, allow_blank: true
  validates_length_of :description, minimum: 5, maximum: 140, allow_blank: true
end

app/models/task.rb
class Task < ApplicationRecord
  belongs_to :project

  enum status: [:in_progress, :done]

  validates :name, presence: true
  validates_length_of :name, minimum: 5, maximum: 40
end

app/models/user.rb
class User < ApplicationRecord
  has_many :projects
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
end

app/controllers/projects_controller.rb
class ProjectsController < ApplicationController
  before_action :find_project, only: [:show, :edit, :update, :destroy]
  def index
    if user_signed_in?
      @projects = Project.where(user_id: current_user.id)
                         .order(id: :desc).paginate(page: params[:page], per_page: 3)
    end
  end

  def show
    @tasks = @project.tasks.paginate(page: params[:page], per_page: 3)
  end

  def new
    @project = current_user.projects.build
  end

  def create
    @project = current_user.projects.build(project_params)
    if @project.save
      redirect_to root_path
    else
      render 'new'
    end
  end

  def edit; end

  def update
    if @project.update(project_params)
      redirect_to project_path(@project)
    else
      render 'edit'
    end
  end

  def destroy
    @project.destroy
    redirect_to root_path
  end

  private

  def project_params
    params.require(:project).permit(:name)
  end

  def find_project
    @project = Project.find(params[:id])
  end
end

app/controllers/tasks_controller.rb
class TasksController < ApplicationController
  before_action :find_task, except: %i[new create]
  before_action :find_project

  def new
    @task = @project.tasks.build
  end

  def create
    @task = @project.tasks.build(task_params)
    if @task.save
      redirect_to root_path
    else
      render 'new'
    end
  end

  def update
    if @task.update(task_params)
      redirect_to project_path(@project)
    else
      render 'edit'
    end
  end

  def destroy
    @task.destroy
    redirect_to root_path
  end

  private

  def task_params
    params.require(:task).permit(:name, :status)
  end

  def find_task
    @task = Task.find(params[:id])
  end

  def find_project
    @project = Project.find(params[:project_id])
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/projects_helper.rb
module ProjectsHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>RgTestTask</title>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag 'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_pack_tag 'application', 'data-turbolinks-track': 'reload' %>
    <link rel="stylesheet" href="//maxcdn.bootstrapcdn.com/font-awesome/4.3.0/css/font-awesome.min.css">
  </head>

  <body>

  <nav class="navbar navbar-default">
    <div class="container">
      <div class="navbar-header">
      <%= link_to "Project", root_path, class: "navbar-brand" %>
      </div>
      <ul class="nav navbar-nav">
        <li><%= link_to "Sign Up", new_user_registration_path %></li>
        <% if current_user.present? %>
          <li><%= link_to "Sign Out", destroy_user_session_path, method: :delete %></li>
        <% else %>
          <li><%= link_to "Log In", new_user_session_path %></li>
        <% end %>
      </ul>
      <% if user_signed_in? %>
        <%= link_to "New Project", new_project_path, class: "navbar-text navbar-link navbar-right" %>
      <% end %>
    </div>
  </nav>

  <p class="notice"><%= notice %></p>
  <p class="alert"><%= alert %></p>

  <div class="container">
    <%= yield %>  
  </div>
    
  </body>
</html>

app/views/projects/_form.html.erb
<%= simple_form_for @project do |f| %> 
  <%= f.input :name, label: "Project" %>
  <%= f.button :submit %>
<% end %>

app/views/projects/_static_landing_page.html.erb
<div class="jumbotron"> 
  <h1>Welcome to your Project</h1> 
  <p>Keep track of your stuff.</p> 
  <%= link_to "Sign Up", new_user_registration_path, class: "btn btn-primary" %> 
  <%= link_to "Log In", new_user_session_path, class: "btn btn-primary" %> 
</div>

app/views/projects/edit.html.erb
<div class="col-md-6 col-md-offset-3">
  <h1>Edit Projects list</h1>

  <%= render 'form' %>
</div>

app/views/projects/index.html.erb
<% if user_signed_in? %>
	<div class="col-md-6 col-md-offset-3">
		<% @projects.each do |project| %>
			<div class="index-wrapper">	
					<div class="row projects">
						<div class="col-md-8">
							<h2 class="project-name"><%= link_to project.name, project %></h2>
							<p style="opacity: 0.5;" class="time-created-at projects-sub-name">Created <%= time_ago_in_words(project.created_at) %> ago</p>
						</div>
						<div class="col-md-2">
							<p><%= link_to project, method: :delete, data: { confirm: "Are you sure?" } do %></p>
								<i class="fa fa-trash fa-lg"></i>
							<% end %>
              <p><%= link_to edit_project_path(project) do %></p>
								<i class="fa fa-pencil-square-o" aria-hidden="true"></i>
							<% end %>
						</div>
					</div>
			</div>

		<% end %>	
    <center><%= will_paginate @projects %></center>
	</div>
  
<% else %>
	<%= render 'static_landing_page' %>
<% end %>	

app/views/projects/new.html.erb
<div class="col-md-6 col-md-offset-3">
  <h1> Add new Project </h1>

  <%= render 'form' %>
</div>

app/views/projects/show.html.erb
<center><%= link_to "New Task", new_project_task_path(@project), class: "navbar-text navbar-link navbar-right" %></center>
<div class="col-md-6 col-md-offset-3">

  <h2><%= @project.name %></h2>

  <%= link_to "Back", root_path %> 
  <%= link_to "Edit", edit_project_path(@project) %> 
  <%= link_to "Delete", project_path(@project), method: :delete, data: { confirm: 'Are you sure?' } %>

  <%= render partial: "/tasks/table", locals: {tasks: @tasks, project: @project} %>
</div>

app/views/tasks/_form.html.erb
<%= simple_form_for [@project, @task] do |f| %> 
  <%= f.input :name, label: "Task" %>
  <%= f.button :submit %>
<% end %>

app/views/tasks/_table.html.erb
	<div class="col-md-6 col-md-offset-3">
		<% tasks.each do |task| %>
			<div class="index-wrapper">	
					<div class="row tasks">
						<div class="col-md-8">
							<h2 class="task-name"><%= task.name %></h2>
						</div>
						<div class="col-md-2">
							<p><%= link_to project_task_path(project, task), method: :delete, data: { confirm: "Are you sure?" } do %></p>
								<i class="fa fa-trash fa-lg"></i>
							<% end %>
              <p><%= link_to edit_project_task_path(project, task) do %></p>
								<i class="fa fa-pencil-square-o" aria-hidden="true"></i>
							<% end %>
						</div>
					</div>
			</div>

		<% end %>	
    <center><%= will_paginate @tasks %></center>
	</div>

app/views/tasks/edit.html.erb
<div class="col-md-6 col-md-offset-3">
  <h1>Edit Tasks list</h1>

  <%= render 'form' %>
</div>

app/views/tasks/new.html.erb
<div class="col-md-6 col-md-offset-3">
  <h1> Add new Task </h1>

  <%= render 'form' %>
</div>